// GENERATED by tool/gen_crypto_vectors.py (independent Python implementation:
// argon2-cffi reference Argon2id, hashlib BLAKE2b, pyca ChaCha20-Poly1305 +
// HChaCha20). Do not edit by hand: these pin the on-disk/on-server format.
// ignore_for_file: constant_identifier_names

const goldenPassword = '\ufee3\ufeae\ufea3\ufe92\ufe8e Vault-2026!';
const goldenPasswordNfkcHex = 'd985d8b1d8add8a8d8a7205661756c742d3230323621';
const goldenSaltHex = '101112131415161718191a1b1c1d1e1f';
const goldenMasterKeyHex =
    '26bbe5101bfcd58647fcccb478907c7b697977fc494861794fb3fe03d19b5eae';
const goldenKekHex =
    'fb620a6d1853802bb262c3155384cdd16fd0e42383e06304c8f7645551fb2371';
const goldenAuthSecret = 'OlLNKquABInIyXf8iAXctmcyUzGj7B5SQB7Aj4ACp3k';
const goldenVaultKeyHex =
    'c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf';
const goldenEntryKeyHex =
    '2a3826571ac683dc417d44835fac7b32cbab5e5cb9f6ba6a1cbc4e1ef47561fd';
const goldenDbKeyHex =
    '46dbb42d393f3fde324585df590dee61c8ccca584a738f79d50376c5b6e45dfb';
const goldenVkByPassword =
    'AaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoYRs0oSEIHBW4o7XL7hvDlzQDp1nU1tswLL5m7A8D3tk89n4kkUTDOkUYAYh+7+lVA==';
const goldenVkByRecovery =
    'AbKysrKysrKysrKysrKysrKysrKysrKysja+2pxQapMsK1bZ4ZKhv1k5PpVKF3lOi0k4UceKbZQ0dxWahl3pq3/gkBLHvwLjDQ==';
const goldenRecoveryText =
    '04106-1050R-3GG28-A1C60-T3GF2-08H44-RM2MB-1E60S-38DHR-78Y3W-G2VK0';
const goldenRecoveryAuthSecret = 'BZZa81E16AAkMzMYFadzJ0XaZXsJxQptF8kTYiJaDcw';
const goldenEntryId = '7d3f0a52-2b4e-4c1a-9f0e-0c6f1d2a9b11';
const goldenEntryPlaintextHex =
    '7b227469746c65223a22d8a8d986d983222c22757365726e616d65223a2275736572406578616d706c652e636f6d222c2270617373776f7264223a22304f6c49317c636f7272656374227d';
const goldenEntryEnvelope =
    'AcPDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw4iXbdusSLnpKltCjLtTFk16QTydfF4PGNEUGirymy7kk1vmdL4hR+wVGIzjZK0OUBIRYhOc39YQYS9Gxt8/WorCP4fCUl5CQtuof7WCXG6miHgTxh1dZ/AXQUEVnS7g3HvxRR3Y7hOTI1xt3mPuF73D5MyKLINMPKu6zE46pIFk2QssXEIsfEZMagLj6kGEUw==';
