#!/usr/bin/env python3
"""Independent re-implementation of the Khazna crypto format.

Generates the golden vectors in test/core/crypto/vectors.dart. It shares no
code with libsodium:
  * Argon2id   -> argon2-cffi (PHC reference implementation)
  * BLAKE2b    -> CPython hashlib
  * XChaCha20-Poly1305 -> HChaCha20 (below) + pyca/cryptography ChaCha20Poly1305
If the Dart/libsodium code and this script agree, the format is pinned.

Usage: pip install argon2-cffi cryptography
       python3 tool/gen_crypto_vectors.py > test/core/crypto/golden_vectors.dart
"""
import base64, hashlib, struct, unicodedata
from argon2.low_level import hash_secret_raw, Type
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

def rotl(v, c): return ((v << c) & 0xffffffff) | (v >> (32 - c))

def qr(s, a, b, c, d):
    s[a] = (s[a] + s[b]) & 0xffffffff; s[d] = rotl(s[d] ^ s[a], 16)
    s[c] = (s[c] + s[d]) & 0xffffffff; s[b] = rotl(s[b] ^ s[c], 12)
    s[a] = (s[a] + s[b]) & 0xffffffff; s[d] = rotl(s[d] ^ s[a], 8)
    s[c] = (s[c] + s[d]) & 0xffffffff; s[b] = rotl(s[b] ^ s[c], 7)

def hchacha20(key, nonce16):
    s = list(struct.unpack('<4I', b'expand 32-byte k')) + list(struct.unpack('<8I', key)) + list(struct.unpack('<4I', nonce16))
    for _ in range(10):
        qr(s,0,4,8,12); qr(s,1,5,9,13); qr(s,2,6,10,14); qr(s,3,7,11,15)
        qr(s,0,5,10,15); qr(s,1,6,11,12); qr(s,2,7,8,13); qr(s,3,4,9,14)
    return struct.pack('<8I', *(s[0:4] + s[12:16]))

def xchacha_encrypt(key, nonce24, msg, ad):
    sub = hchacha20(key, nonce24[:16])
    return ChaCha20Poly1305(sub).encrypt(b'\0\0\0\0' + nonce24[16:], msg, ad)

def kdf(key, ctx, i, n=32):
    return hashlib.blake2b(b'', key=key, salt=struct.pack('<Q', i) + bytes(8),
                           person=ctx.encode() + bytes(8), digest_size=n).digest()

def seal(key, ctx, nonce, pt):
    return bytes([1]) + nonce + xchacha_encrypt(key, nonce, pt, f'vaultsnap/v1/{ctx}'.encode())

def pad(b, block):  # ISO/IEC 7816-4, as sodium_pad
    out = b + b'\x80'
    return out + bytes((-len(out)) % block)

CROCK = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
def crockford(b):
    bits = ''.join(f'{x:08b}' for x in b); bits += '0' * ((-len(bits)) % 5)
    s = ''.join(CROCK[int(bits[i:i+5], 2)] for i in range(0, len(bits), 5))
    return '-'.join(s[i:i+5] for i in range(0, len(s), 5))

# Self-check the XChaCha construction against libsodium's published vector
# (test/default/aead_xchacha20poly1305.c / .exp).
k = bytes(range(0x80, 0xa0)); n = bytes([7,0,0,0]) + bytes(range(0x40, 0x54))
ad = bytes([0x50,0x51,0x52,0x53,0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7])
m = b"Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it."
assert xchacha_encrypt(k, n, m, ad).hex().startswith('f8ebea4875044066fc162a06'), 'HChaCha20 self-check failed'
assert xchacha_encrypt(k, n, m, ad).hex().endswith('8420')
# Self-check BLAKE2b KDF against libsodium's published vector (test/default/kdf.exp).
assert kdf(bytes(range(32)), 'KDF test', 0, 64).hex().startswith('a0c724404728c8bb')

# ---- Golden vault ----------------------------------------------------------
password = 'ﻣﺮﺣﺒﺎ Vault-2026!'  # Arabic presentation forms
pw_bytes = unicodedata.normalize('NFKC', password).encode()
salt = bytes(range(0x10, 0x20))
master = hash_secret_raw(pw_bytes, salt, 3, 65536, 1, 32, Type.ID)
kek, auth = kdf(master, 'VSnapKEK', 1), kdf(master, 'VSnapAUT', 1)
vault_key = bytes(range(0xc0, 0xe0))
recovery = bytes(range(1, 33))
rkek, rauth = kdf(recovery, 'VSnapRCV', 1), kdf(recovery, 'VSnapRCV', 2)
vk_pw = seal(kek, 'wrap/masterPassword', bytes([0xa1]) * 24, vault_key)
vk_rc = seal(rkek, 'wrap/recoveryKey', bytes([0xb2]) * 24, vault_key)
entry_key, db_key = kdf(vault_key, 'VSnapENT', 1), kdf(vault_key, 'VSnapDB_', 1)
entry_id = '7d3f0a52-2b4e-4c1a-9f0e-0c6f1d2a9b11'
entry_pt = '{"title":"بنك","username":"user@example.com","password":"0OlI1|correct"}'.encode()
entry_ct = seal(entry_key, f'entry/{entry_id}', bytes([0xc3]) * 24, pad(entry_pt, 128))
checksum = hashlib.blake2b(recovery, digest_size=16).digest()[:2]

def b64(b): return base64.b64encode(b).decode()
pw_esc = password.encode('unicode_escape').decode()
print("""// GENERATED by tool/gen_crypto_vectors.py (independent Python implementation:
// argon2-cffi reference Argon2id, hashlib BLAKE2b, pyca ChaCha20-Poly1305 +
// HChaCha20). Do not edit by hand: these pin the on-disk/on-server format.
// ignore_for_file: constant_identifier_names
""")
print(f"""const goldenPassword = '{pw_esc}';
const goldenPasswordNfkcHex = '{pw_bytes.hex()}';
const goldenSaltHex = '{salt.hex()}';
const goldenMasterKeyHex = '{master.hex()}';
const goldenKekHex = '{kek.hex()}';
const goldenAuthSecret = '{base64.urlsafe_b64encode(auth).decode().rstrip('=')}';
const goldenVaultKeyHex = '{vault_key.hex()}';
const goldenEntryKeyHex = '{entry_key.hex()}';
const goldenDbKeyHex = '{db_key.hex()}';
const goldenVkByPassword = '{b64(vk_pw)}';
const goldenVkByRecovery = '{b64(vk_rc)}';
const goldenRecoveryText = '{crockford(recovery + checksum)}';
const goldenRecoveryAuthSecret = '{base64.urlsafe_b64encode(rauth).decode().rstrip('=')}';
const goldenEntryId = '{entry_id}';
const goldenEntryPlaintextHex = '{entry_pt.hex()}';
const goldenEntryEnvelope = '{b64(entry_ct)}';""")
