#!/usr/bin/env python3
"""Keeps lib/services/update/windows_installer.dart in step with apply_update.ps1.

The Dart file holds the script as a raw string constant between the markers

    // BEGIN apply_update.ps1 ...
    // END apply_update.ps1

This tool rewrites that block from tool/windows_update_helper/apply_update.ps1.
Python 3.9+, standard library only. Run from anywhere.

    python3 tool/windows_update_helper/embed_script.py          # rewrite
    python3 tool/windows_update_helper/embed_script.py --check  # exit 1 if stale

A unit test (test/services/update/windows_installer_test.dart) fails when the
two differ, so forgetting to run this shows up in CI.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / 'tool' / 'windows_update_helper' / 'apply_update.ps1'
TARGET = ROOT / 'lib' / 'services' / 'update' / 'windows_installer.dart'

BEGIN = '// BEGIN apply_update.ps1'
END = '// END apply_update.ps1'


def render(script: str) -> str:
    return (
        BEGIN + ' (generated by tool/windows_update_helper/embed_script.py)\n'
        '/// The swap script, byte for byte the file\n'
        '/// `tool/windows_update_helper/apply_update.ps1` (a test checks this).\n'
        "const String windowsApplyUpdateScript = r'''\n"
        + script
        + "''';\n"
        + END
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--check', action='store_true',
                        help='do not write; exit 1 when the Dart copy is stale')
    args = parser.parse_args()

    raw = SCRIPT.read_bytes()
    try:
        script = raw.decode('ascii')
    except UnicodeDecodeError as e:
        print(f'{SCRIPT.name} must be ASCII only (PowerShell 5.1 reads a script '
              f'without BOM as ANSI): {e}', file=sys.stderr)
        return 2
    if '\r' in script:
        print(f'{SCRIPT.name} must use LF line endings', file=sys.stderr)
        return 2
    if "'''" in script:
        print(f"{SCRIPT.name} must not contain three single quotes in a row", file=sys.stderr)
        return 2
    if not script.endswith('\n') or script.endswith('\n\n'):
        print(f'{SCRIPT.name} must end with exactly one newline', file=sys.stderr)
        return 2

    text = TARGET.read_text(encoding='utf-8')
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < start:
        print(f'markers not found in {TARGET}', file=sys.stderr)
        return 2
    new = text[:start] + render(script) + text[end + len(END):]
    if new == text:
        print('up to date')
        return 0
    if args.check:
        print('windows_installer.dart is out of date; run embed_script.py', file=sys.stderr)
        return 1
    TARGET.write_text(new, encoding='utf-8')
    print('updated windows_installer.dart')
    return 0


if __name__ == '__main__':
    sys.exit(main())
